services:

  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        DOMAIN: ${DOMAIN:-wp.local}
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - .:/app
      - ./docker:/docker
    ports:
      - "${WEB_HTTP_PORT:-80}:80"
      - "${WEB_HTTPS_PORT:-443}:443"
      - "${MAILPIT_HTTP_PORT:-8024}:8024"
      - "${MAILPIT_HTTPS_PORT:-8025}:8025"
      - "${PMA_HTTP_PORT:-8000}:8000"
      - "${PMA_HTTPS_PORT:-8001}:8001"
    environment:
      - DOMAIN=${DOMAIN:-wp.local}
    restart: unless-stopped
    depends_on:
      - php
      - db

  php:
    build: docker/php
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file: .env.xdebug
    volumes:
      - ./.env:/.env
      - .:/app
      - ./docker:/docker
      - ./docker/php/config.ini:/usr/local/etc/php/conf.d/config.ini

  node:
    image: node:14
    depends_on:
      - php
    restart: no
    volumes:
      - .:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: sqlr00t
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASSWORD:-SQLs3cr3t}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/sqldump/wordpress.sql:/docker-entrypoint-initdb.d/dump.sql

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
